export const SOCKET_PLAYER_JOINED = "SOCKET_PLAYER_JOINED";
export const SOCKET_PLAYER_READY = "SOCKET_PLAYER_READY";
export const SOCKET_PLAYER_NOT_READY = "SOCKET_PLAYER_NOT_READY";
export const SOCKET_GAME_SETTINGS = "SOCKET_GAME_SETTINGS";

export const SOCKET_GAME_START = "SOCKET_GAME_START";
export const SOCKET_CURRENT_QUESTION = "SOCKET_CURRENT_QUESTION";

export const SOCKET_PLAYER_ANSWERED = "SOCKET_PLAYER_ANSWERED";
export const SOCKET_PLAYER_ANSWERED_OPEN = "SOCKET_PLAYER_ANSWERED_OPEN";
export const SOCKET_OPEN_TO_RECIPIENT = "SOCKET_OPEN_TO_RECIPIENT";

export const SOCKET_QUESTION_COMPLETE = "SOCKET_QUESTION_COMPLETE";
export const SOCKET_QUESTION_RESULTS = "SOCKET_QUESTION_RESULTS";
export const SOCKET_NEXT_QUESTION = "SOCKET_NEXT_QUESTION";
export const SOCKET_GAME_OVER = "SOCKET_GAME_OVER";

export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";
export const SOCKET_ANSWERED_QUESTIONS = "SOCKET_ANSWERED_QUESTIONS";
export const SOCKET_ANSWERED_PLAYERS = "SOCKET_ANSWERED_PLAYERS";

export const VIEWER_READY = "VIEWER_READY";
export const VIEWER_ANSWER = "VIEWER_ANSWER";
export const VIEWER_SETTING = "VIEWER_SETTING";