export const SOCKET_PLAYER_JOINED = "SOCKET_PLAYER_JOINED";
export const SOCKET_PLAYER_READY = "SOCKET_PLAYER_READY";
export const SOCKET_PLAYER_NOT_READY = "SOCKET_PLAYER_NOT_READY";

export const SOCKET_GAME_START = "SOCKET_GAME_START";
export const SOCKET_CURRENT_QUESTION = "SOCKET_CURRENT_QUESTION";

export const SOCKET_PLAYER_ANSWERED = "SOCKET_PLAYER_ANSWERED";
export const SOCKET_QUESTION_COMPLETE = "SOCKET_QUESTION_COMPLETE";
export const SOCKET_QUESTION_RESULTS = "SOCKET_QUESTION_RESULTS";
export const SOCKET_GAME_OVER = "SOCKET_GAME_OVER";

export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";

export const VIEWER_READY = "VIEWER_READY";
export const VIEWER_ANSWER = "VIEWER_ANSWER";